services:
  rabbitmq:
    image: rabbitmq:3-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=username
      - RABBITMQ_DEFAULT_PASS=password

  postgres:
    image: postgres:latest
    container_name: leetcode_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: leetcode
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  rabbitmq-data:
  postgres_data:
